services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    restart: 'always'
    env_file:
      - ./.env

  nginx:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    restart: 'always'
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - ${FRONTEND_PORT}:80
    depends_on:
      - backend
    env_file:
      - ./.env
